openapi: 3.1.0

info:
  title: Tag store
  description: |
    Tag store associates [semver version numbers](https://semver.org/) with tree node entries.
  version: 0.1.0

paths:
  /:
    $ref: '#/components/pathItems/Tag'

  /{tag}:
    $ref: '#/components/pathItems/TagName'

components:
  schemas:
    Tag:
      description: An immutable mapping of a [semver version number](https://semver.org/) to a tree node entry.
      type: string
      pattern: ^[a-zA-Z0-9-.]+$
      example: v1.2.3

    Entry:
      description: A tree node entry.
      type: object
      required:
        - hash
      properties:
        hash:
          type: string
          pattern: ^sha(224|256|384|512):[a-zA-Z0-9-_]+$
          example: sha384:mqVuAfXRKap7bdgcCY5uykM6-R9GqQ8K_uxy9rx7HNQlGYl1kPzQho1wx4JwY8wC

  pathItems:
    Tag:
      get:
        description: List available tags.
        responses:
          '200':
            description: Available tags sorted lexicographically
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Tag'
                  example:
                    - v0.5.3
                    - v1.2.3
                    - v1.2.4
                    - v2.0.1-rc1
  
    TagName:
      parameters:
        - name: tag
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Tag'
      head:
        description: Check whether a tag exists.
        responses:
          '200':
            description: Tag exists
          '404':
            description: Tag does not exist
      get:
        description: Get a tree node entry associated with a tag.
        responses:
          '200':
            description: Tree node entry associated with the tag
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Entry'
          '404':
            description: Tag does not exist
      put:
        description: Associate a tree node entry with a tag.
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entry'
        responses:
          '201':
            description: Tag associated with a tree node entry
          '204':
            description: Tag already exists and matches the tree hash
          '404':
            description: Tree node does not exist
      delete:
        description: Yank a tag.
        responses:
          '204':
            description: Tag yanked
          '404':
            description: Tag does not exist
