[package]
name = "drawbridge-app"
version = "0.1.0"
authors = ["Profian Inc"]
edition = "2021"

[dependencies]
# Internal dependencies
drawbridge-jose = { path = "../jose" }
drawbridge-store = { path = "../store" }
drawbridge-type = { path = "../type", features = ["server"] }

# External dependencies
axum = { version = "0.5.4", default-features = false, features = ["json"] }
futures = { version = "0.3.21" }
mime = "0.3.16"
serde = { version = "1.0.136" }
serde_json = "1.0.79"
tokio = { version = "1.17.0" }
tower = { version = "0.4.12" }

[dev-dependencies]
reqwest = { version = "0.11.10", features = ["json"] }
tokio = { version = "1.17.0", features = ["macros", "rt"] }
