[package]
name = "drawbridge-app"
version = "0.1.0"
authors = ["Profian Inc"]
edition = "2021"

[dependencies]
# Internal dependencies
drawbridge-jose = { path = "../jose" }
drawbridge-store = { path = "../store" }
drawbridge-type = { path = "../type", features = ["server"] }

# External dependencies
axum = { version = "0.5.4", default-features = false, features = ["json"] }
futures = { version = "0.3.21", default-features = false }
mime = { version = "0.3.16", default-features = false }
serde = { version = "1.0.136", default-features = false }
serde_json = { version = "1.0.79", default-features = false, features = ["std"] }
tokio = { version = "1.17.0", default-features = false }
tower = { version = "0.4.12", default-features = false }

[dev-dependencies]
reqwest = { version = "0.11.10", default-features = false, features = ["json"] }
tokio = { version = "1.17.0", default-features = false, features = ["macros", "rt"] }
