[package]
name = "drawbridge-byte"
version = "0.1.0"
authors = ["Profian Inc"]
edition = "2021"

[dependencies]
# Internal dependencies

# External dependencies
base64 = { version = "0.13.0", default-features = false, features = ["std"] }
serde = { version = "1.0.136", default-features = false, features = ["std"], optional = true }
