[package]
name = "drawbridge-byte"
version = "0.1.0"
authors = ["Profian Inc"]
edition = "2021"

[dependencies]
# Internal dependencies

# External dependencies
base64 = "0.13.0"
serde = { version = "1.0.136", features = ["derive"] }
