[package]
name = "drawbridge-bin"
version = "0.1.0"
authors = ["Profian Inc"]
edition = "2021"

[dependencies]
axum = "0.4.8"
tokio = { version = "1.17.0", features = ["full"] }
tower = "0.4.12"

drawbridge = { path = "./.." }

[workspace]
