openapi: 3.1.0

info:
  title: Drawbridge
  description: |
    Drawbridge is a combination of:
      - Content-addressable store of arbitrary data (trees).
      - Tag store mapping [semver version numbers](https://semver.org/) to tree node entries.

    Definition of items used by the Drawbridge:
    - Node entry: combination of a hash of the inherent properies of the node and arbirary exherent properties of the node (for example, `from`).
    - Node: either a file or a directory, where directory is a collection of node entries.
      - All nodes have contents associated with them:
        - For directory nodes: key-value object with keys representing the node names and values representing node entries.
        - For file nodes: raw file contents of an arbitrary [`Content-Type`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) other than `"application/vnd.drawbridge.directory.v1+json"`
      - All nodes have a [`Content-Type`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) associated with them.
        - Value of `"application/vnd.drawbridge.directory.v1+json"` identifies a directory node.
        - All other values identify a file node.
      - All nodes have a [`Content-Length`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) associated with them.
        - Value for directory nodes is equal to byte length of JSON-encoded directory contents without whitespace characters.
        - Value for file nodes is equal to byte length of raw file contents.
      - All nodes have a [`Content-Digest`](https://www.ietf.org/archive/id/draft-ietf-httpbis-digest-headers-08.html#name-the-content-digest-field) associated with them.
        - Value for directory nodes is equal to hash of JSON-encoded directory contents without whitespace characters.
        - Value for file nodes is equal to hash of raw file contents.
      - All nodes are uniquely identified by the hash of their inherent properties (metadata), which is computed over JSON-encoded object with lexicographically-sorted keys
        with the following contents without whitespace characters:
        - For directory nodes:
            ```
            {
              "contentDigest": <object mapping digest algorithms to base64-encoded digests of JSON-encoded directory contents with lexicographically-sorted keys without whitespace characters>,
              "contentLength": <byte length of JSON-encoded directory contents without whitespace characters>,
              "contentType": "application/vnd.drawbridge.directory.v1+json",
            }
            ```
            For example, `sha384` hash computed over following directory node metadata:
            ```
            {"contentDigest":{"sha384":"DH01Tx3ixOrDYbNcjqw-H53EIFSI232hbotDTy1E_NU6+qodYhdrswrXoEfx_nnx"},"contentLength":134,"contentType":"application/vnd.drawbridge.directory.v1+json"}
            ```
            is equal to:
            ```
            7GZOiJ7WwbJ2PKz3iZ2Vt_NHNz65guUjQZ_uo6o2LYkbO_Al8pImelhUBJCReJw-
            ```
        - For file nodes:
            ```
            {
              "contentDigest": <object mapping digest algorithms to base64-encoded digests of raw file contents>,
              "contentLength": <byte length of raw file contents>,
              "contentType": <arbitrary media type other than "application/vnd.drawbridge.directory.v1+json">,
            }
            ```
            For example, `sha384` hash computed over following directory node metadata:
            ```
            {"contentDigest":{"sha384":"mqVuAfXRKap7bdgcCY5uykM6-R9GqQ8K_uxy9rx7HNQlGYl1kPzQho1wx4JwY8wC"},"contentLength":42,"contentType":"text/plain"}
            ```
            is equal to:
            ```
            _a5zhtfOOuID4PIn0Epd8Agv46bBv53Xdizg02BGXtSk2B8YEdggchYqw-_PpDb_
            ```
      - A node can only be uploaded once. After the node is uploaded, it cannot be reuploaded.
      - A node may belong to multiple trees.
      - A node in a directory is identified by a case-sensitive name consisting of alphanumeric characters, dashes and underscores
        and must represent valid URL string, which is unique within a directory.
    - Tree: a top-level node uniquely identified by it's hash.
      - A tree is uniquely identified by it's hash, which is computed over the contents of the tree. The tree is therefore content-addressable and represents a [Merkle tree](https://en.wikipedia.org/wiki/Merkle_tree) by definition.
      - A tree can be yanked, which means that it cannot be downloaded anymore.
    - Tag: an immutable mapping of a [semver version number](https://semver.org/) to a tree hash.
      - An existing tag can be yanked, which means that it cannot be resolved anymore.
  version: 0.1.0

paths:
  /_tree/{algo}:
    $ref: '../crates/tree/api/api.yml#/components/pathItems/Algo'

  /_tree/{algo}/{hash}:
    $ref: '../crates/tree/api/api.yml#/components/pathItems/AlgoHash'

  /_tree/{algo}/{hash}/{path}:
    $ref: '../crates/tree/api/api.yml#/components/pathItems/AlgoHashPath'

  /_tag:
    $ref: '../crates/tags/api/api.yml#/components/pathItems/Tag'

  /_tag/{tag}:
    $ref: '../crates/tags/api/api.yml#/components/pathItems/TagName'
