name: "Lint"
on: [ push, pull_request ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Setup Rust toolchain
      run: rustup show
    - name: cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - name: cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --workspace
