[package]
name = "drawbridge-tags"
version = "0.1.0"
authors = ["Profian Inc"]
edition = "2021"

[dependencies]
tide = "0.16.0"
cap-async-std = { version = "0.24.2" }
serde = { version = "1.0.136", features = ["derive"] }
