[package]
name = "drawbridge-tags"
version = "0.1.0"
authors = ["Profian Inc"]
edition = "2021"

[dependencies]
# Internal Dependencies
drawbridge-hash = { path = "../hash" }
drawbridge-tree = { path = "../tree" }
drawbridge-type = { path = "../type" , features = ["server"]}
drawbridge-jose = { path = "../jose" }

axum = "0.5.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
semver = { version = "1.0.6", features = ["serde"] }
tokio = { version = "1.17.0" }
